"""
Django settings for proa project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import dj_database_url
from dotenv import load_dotenv
from corsheaders.defaults import default_headers


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / '.env')
load_dotenv(BASE_DIR / '.env')


#API DE GOOGLE
#GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("KEY_SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG") == "True"



AUTH_USER_MODEL = 'usuario.Usuario'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',
    'core',
    'academico',
    'usuario',
    'foro',
    'aula_virtual',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist', 
    'corsheaders',   
    'channels',
    'notificacion',
    'mensajeria',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

# Medición de consultas y tiempos (core/middleware.py): solo en desarrollo
if DEBUG:
    MIDDLEWARE.insert(0, 'core.middleware.MedicionMiddleware')

AUTHENTICATION_BACKENDS = [
    'usuario.backends.DNIBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Un solo formato de error en toda la API: {'detail': ...} o errores por campo (core/exceptions.py)
    'EXCEPTION_HANDLER': 'core.exceptions.manejador_de_excepciones',
    # Throttling (core/throttling.py). Con más de un worker de uvicorn el contador debe vivir en Redis
    # (REDIS_URL): con la caché en memoria cada proceso cuenta por separado y el límite se multiplica.
    # Cantidad de proxies de confianza delante de la app (solo nginx): DRF toma la IP que ese proxy agregó
    # al final de X-Forwarded-For y no los valores que envía el cliente. nginx debe PISAR la cabecera.
    'NUM_PROXIES': int(os.getenv('NUM_PROXIES', '1')),
    # Por IP (login, recuperacion, recuperacion_confirmar) y por cuenta (login_dni, recuperacion_email)
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'recuperacion': '3/hour',
        'recuperacion_confirmar': '5/hour',
        'login_dni': '10/hour',
        'recuperacion_email': '3/hour',
        'mensajes': '30/min',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'PROAConecta API',
    'DESCRIPTION': 'Documentación interactiva de materias, asignaciones e inscripciones',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=300),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

ROOT_URLCONF = 'proa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
        # DB_SSL=False en el compose local (Postgres sin TLS); por defecto sigue exigiendo SSL (base en la nube)
        ssl_require=os.getenv('DB_SSL', 'True').lower() in ('true', '1', 'yes'),
    )
}
# Correo y Discord salen en un hilo después del commit (integraciones/fondo.py). Con True corren en
# línea: lo usan los tests para ser deterministas
SEGUNDO_PLANO_SINCRONO = False

# --- Discord
DISCORD_WEBHOOK_URL = os.getenv('DISCORD_WEBHOOK_URL')

# --- Nueva configuración MongoDB Atlas ---

MONGO_URI = os.getenv("DATABASE_URL_MONGODB")
MONGO_DB_NAME = os.getenv("MONGO_DB_NAME", "proa_conecta")

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
PASSWORD_RESET_TIMEOUT = 900

ALLOWED_HOSTS = [
   '127.0.0.1',
    'localhost',
    '0.0.0.0',
    'testserver'
]


CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',
    'http://127.0.0.1:4200',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]


CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = list(default_headers) +[
    'authorization',
    'content-type',
    'x-csrftoken',
]

# El navegador solo deja leer estas cabeceras de medición si se exponen (solo existen con DEBUG)
CORS_EXPOSE_HEADERS = ['X-Query-Count', 'X-Response-Time-ms']

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

ASGI_APPLICATION = 'proa.asgi.application'
# --- CONFIGURACIÓN DE CORREO ELECTRÓNICO ---
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', f"PROA Conecta <{EMAIL_HOST_USER or 'noreply@proaconecta.edu.ar'}>")


# URL base del cliente frontend 
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:4200')

# Con REDIS_URL (compose) los WebSockets funcionan entre procesos; sin ella queda en memoria
REDIS_URL = os.getenv('REDIS_URL')

# La caché guarda los tickets del WebSocket: con Redis es compartida entre procesos, sin él es local
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

if not DEBUG and not REDIS_URL:
    import logging

    # La caché local y el channel layer en memoria no se comparten entre workers
    logging.getLogger(__name__).warning(
        "REDIS_URL no está definida con DEBUG desactivado: la caché local y el channel layer en memoria "
        "no funcionan entre varios workers, por lo que los tickets y los eventos de WebSocket pueden fallar."
    )
