# Generated by Django 6.0.6 on 2026-10-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='actividades/%Y/%m/')),
                ('enlace', models.URLField(blank=True, max_length=500, null=True)),
                ('permitir_entrega_tardia', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada')], default='PUBLICADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.materia')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregas/%Y/%m/')),
                ('enlace', models.URLField(blank=True, max_length=500, null=True)),
                ('contenido_texto', models.TextField(blank=True, null=True)),
                ('fuera_de_termino', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENTREGADO', 'Entregado'), ('NO_ENTREGADO', 'No entregado'), ('CORREGIDO', 'Corregido')], default='ENTREGADO', max_length=20)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='aula_virtual.actividad')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='usuario.persona')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entrega',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, help_text='Escala del 1.00 al 10.00', max_digits=4)),
                ('descripcion', models.TextField(blank=True, help_text='Devolución del profesor', null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota', to='aula_virtual.entrega')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_asentadas', to='usuario.persona')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('visible', models.BooleanField(default=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='academico.materia')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidad',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales/%Y/%m/')),
                ('enlace', models.URLField(blank=True, max_length=500, null=True)),
                ('tipo', models.CharField(choices=[('DOCUMENTO', 'Documento'), ('VIDEO', 'Video'), ('ENLACE', 'Enlace externo')], default='DOCUMENTO', max_length=20)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='academico.materia')),
                ('unidad', models.ForeignKey(blank=True, help_text='Si es NULL es un recurso general. Si tiene ID pertenece a una unidad.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='aula_virtual.unidad')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'material',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='unidad',
            field=models.ForeignKey(blank=True, help_text='Si es NULL, es una actividad general. Si tiene ID pertenece a una unidad.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='aula_virtual.unidad'),
        ),
        migrations.AddConstraint(
            model_name='entrega',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_baja__isnull', True)), fields=('actividad', 'estudiante'), name='unique_entrega_actividad_estudiante'),
        ),
    ]
