# Generated by Django 6.0.6 on 2026-10-05 17:56

from django.db import migrations, models
from django.db.models import Count


def verificar_sin_duplicados(apps, schema_editor):
    # Nunca borra ni da de baja datos: si hay duplicados activos, aborta y lista los conflictos
    Unidad = apps.get_model('aula_virtual', 'Unidad')
    duplicados = (
        Unidad.objects.filter(fecha_baja__isnull=True)
        .values('materia_id', 'titulo')
        .annotate(cantidad=Count('id'))
        .filter(cantidad__gt=1)
        .order_by('materia_id', 'titulo')
    )
    if duplicados:
        detalle = '; '.join(
            f"materia {d['materia_id']}: '{d['titulo']}' ({d['cantidad']} unidades)" for d in duplicados
        )
        raise RuntimeError(
            'No se puede crear la restricción unique_unidad_titulo_materia: hay unidades activas con el mismo '
            f'título en la misma materia ({detalle}). Resolvelas a mano antes de migrar '
            '(renombrar o dar de baja las sobrantes) siguiendo planning/changes/backend.md, entrada A2.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('aula_virtual', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(verificar_sin_duplicados, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_baja__isnull', True)), fields=('materia', 'titulo'), name='unique_unidad_titulo_materia'),
        ),
    ]
