# Generated by Django 6.0.6 on 2026-10-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_baja_logica_de_materias'),
        ('aula_virtual', '0002_unidad_titulo_unico_por_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='academico.materia'),
        ),
        migrations.AlterField(
            model_name='material',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales', to='academico.materia'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='academico.materia'),
        ),
    ]
