# Generated by Django 6.0.6 on 2026-10-06 19:04

import core.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0003_baja_logica_de_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to=core.storage.RutaUnica('actividades'), validators=[core.validators.validar_archivo]),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=core.storage.RutaUnica('entregas'), validators=[core.validators.validar_archivo]),
        ),
        migrations.AlterField(
            model_name='material',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=core.storage.RutaUnica('materiales'), validators=[core.validators.validar_archivo]),
        ),
    ]
