# Generated by Django 6.0.6 on 2026-10-09 17:40

from django.db import migrations, models


def verificar_notas_en_rango(apps, schema_editor):
    """Aborta con un mensaje claro si hay notas que violarían la restricción de rango."""
    Nota = apps.get_model('aula_virtual', 'Nota')
    fuera_de_rango = Nota.objects.filter(
        models.Q(calificacion__lt=1) | models.Q(calificacion__gt=10)
    ).count()
    if fuera_de_rango:
        raise RuntimeError(
            f'No se puede aplicar la restricción de rango: hay {fuera_de_rango} nota(s) con calificación '
            'fuera de 1 a 10. Corríjalas antes de migrar. Consulta para encontrarlas: '
            'SELECT id, entrega_id, calificacion FROM nota WHERE calificacion < 1 OR calificacion > 10'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_baja_logica_de_materias'),
        ('aula_virtual', '0004_archivos_validados_y_con_nombre_unico'),
        ('usuario', '0003_roles_iniciales'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['materia', 'fecha_baja'], name='actividad_materia_baja_idx'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['actividad', 'fecha_baja'], name='entrega_actividad_baja_idx'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['estudiante', 'fecha_baja'], name='entrega_estudiante_baja_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['materia', 'fecha_baja'], name='material_materia_baja_idx'),
        ),
        migrations.RunPython(verificar_notas_en_rango, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.CheckConstraint(condition=models.Q(('calificacion__gte', 1), ('calificacion__lte', 10)), name='nota_calificacion_en_rango'),
        ),
    ]
