# Generated by Django 6.0.6 on 2026-10-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('CURSANDO', 'Cursando'), ('REGULAR', 'Regular'), ('PROMOCIONADO', 'Promocionado'), ('LIBRE', 'Libre'), ('BAJA', 'Baja Administrativa')], default='CURSANDO', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='usuario.persona')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'inscripcion',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('criterios_evaluacion', models.TextField(blank=True, null=True)),
                ('anio', models.PositiveSmallIntegerField(help_text='Año de la materia (por ejemplo, 2026)')),
                ('curso', models.CharField(help_text='Curso de la materia (por ejemplo, 1ro A, 2do C, 3ro A, etc.)', max_length=20)),
                ('discord_webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='materias_inscriptas', through='academico.Inscripcion', to='usuario.persona')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_a_cargo', to='usuario.persona')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materia',
                'ordering': ['-anio', 'curso', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academico.materia'),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.UniqueConstraint(fields=('titulo', 'curso', 'anio'), name='unique_materia_curso_anio'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('materia', 'estudiante'), name='unique_materia_estudiante'),
        ),
    ]
