# Generated by Django 6.0.6 on 2026-10-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('usuario', '0003_roles_iniciales'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materia',
            name='unique_materia_curso_anio',
        ),
        migrations.AddField(
            model_name='materia',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academico.materia'),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_baja__isnull', True)), fields=('titulo', 'curso', 'anio'), name='unique_materia_curso_anio'),
        ),
    ]
